address: Calle Pizarro 527, 04001 Arequipa, Peru
baseurl: ""
category: Sports team
cover: https://scontent-iad3-1.xx.fbcdn.net/v/t39.30808-6/441955024_424291480546953_8528852871920262150_n.png?_nc_cat=101&ccb=1-7&_nc_sid=351699&_nc_ohc=mDyEsjjLk60Q7kNvwEw7BdY&_nc_oc=AdrycYPwrgD3ZVL-AanuIaPc9by_5Oyh5ZJAGfNtXHfc8srXKMwhWqHTJuW6i7D1YAs&_nc_zt=23&_nc_ht=scontent-iad3-1.xx&edm=AJdBtusEAAAA&_nc_gid=E4puJdkMPAbb8O-GC1tgsA&_nc_tpa=Q5bMBQE7bPGBT6U75H7uMzvP5f9wqUtzc8CmsVtX3om_1OzP0qOLGRTRir7Yxh_twGi-AcJjyX9H7GwQOA&oh=00_Af3QK8q4qPV9asIm3B4dTLT8cTJqcecWdyxocSO16NfuZQ&oe=69E21C2C
description: Foot Ball Club Piérola es un club de fútbol del Perú, de la ciudad de
  Arequipa en el Departamento de Arequipa. Fue fundado el 7 de mayo de 1922 y participa
  en la Copa Perú.
domain: fbcpierola.github
email: info@fbcpierola.com
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/
- package.json
- package-lock.json
- webpack.config.js
- styles
- scripts
linklists:
- title: EL CLUB
  url: /club
plugins:
- jekyll-feed
social_networks:
- name: youtube
  public_url: https://www.youtube.com/@fbcpierola
- name: instagram
  public_url: https://www.instagram.com/fbcpierola
- name: facebook
  public_url: https://www.facebook.com/fbcpierola
- name: tiktok
  public_url: https://www.tiktok.com/@fbcpierola
theme: null
title: FBC Piérola
url: https://fbcpierola.com
