address: Calle Pizarro 527, 04001 Arequipa, Peru
baseurl: ""
category: Sports team
cover: https://scontent-fra3-1.xx.fbcdn.net/v/t39.30808-6/441955024_424291480546953_8528852871920262150_n.png?_nc_cat=101&ccb=1-7&_nc_sid=351699&_nc_ohc=HbcSt9OUqP4Q7kNvwGgYnT2&_nc_oc=AdpiFTRDWLtBJ-8xeSOWK-4NeOgoRKTgS8gkLSi8VQVZzDhrAjqkQAMNw85Bd5p-2e0&_nc_zt=23&_nc_ht=scontent-fra3-1.xx&edm=AJdBtusEAAAA&_nc_gid=DvuXw8Cns_-MDqBKe2giRg&_nc_tpa=Q5bMBQE6f-eRlWaCY3xkWHdSqzUkgM_qAU_pmt5iO-_Yb-5zAxQ6JX9GXRJPfIQtkDzmWfEmSpIt0QHksg&oh=00_Af6g_M4o4H5QmXnJMyT5igIbGhJllJT2Y1Dr1g7XCH4STA&oe=69F9D72C
description: Foot Ball Club Piérola es un club de fútbol del Perú, de la ciudad de
  Arequipa en el Departamento de Arequipa. Fue fundado el 7 de mayo de 1922 y participa
  en la Copa Perú.
domain: fbcpierola.github
email: info@fbcpierola.com
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/
- package.json
- package-lock.json
- webpack.config.js
- styles
- scripts
linklists:
- title: EL CLUB
  url: /club
plugins:
- jekyll-feed
social_networks:
- name: youtube
  public_url: https://www.youtube.com/@fbcpierola
- name: instagram
  public_url: https://www.instagram.com/fbcpierola
- name: facebook
  public_url: https://www.facebook.com/fbcpierola
- name: tiktok
  public_url: https://www.tiktok.com/@fbcpierola
theme: null
title: FBC Piérola
url: https://fbcpierola.com
