address: Calle Pizarro 527, 04001 Arequipa, Peru
baseurl: ""
category: Sports team
cover: https://scontent-iad3-1.xx.fbcdn.net/v/t39.30808-6/441955024_424291480546953_8528852871920262150_n.png?_nc_cat=101&ccb=1-7&_nc_sid=351699&_nc_ohc=Q4yxvrmm0XsQ7kNvwE5cbct&_nc_oc=AdrgqE3Dud6Q9vpwL_bdr7VIH30OxNLWb8hnYSmKo4GwSrhWR9KBm3lEONNBU2KafZ4&_nc_zt=23&_nc_ht=scontent-iad3-1.xx&edm=AJdBtusEAAAA&_nc_gid=ec6Fti4FpyK0hCnGL3UHjA&_nc_tpa=Q5bMBQHMrMrr56mmCjJ_scE1z4oZMEpVoNF_BA8S5PmxnPDU7USu_b3bxjHp7H5E5Aamzo2f4IzAtUjFng&oh=00_AfzuP7uZWkweuNenZwlr2zoDEQA2T8cnbgj2yx2ime-zsQ&oe=69C90FAC
description: Foot Ball Club Piérola es un club de fútbol del Perú, de la ciudad de
  Arequipa en el Departamento de Arequipa. Fue fundado el 7 de mayo de 1922 y participa
  en la Copa Perú.
domain: fbcpierola.github
email: info@fbcpierola.com
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/
- package.json
- package-lock.json
- webpack.config.js
- styles
- scripts
linklists:
- title: EL CLUB
  url: /club
plugins:
- jekyll-feed
social_networks:
- name: youtube
  public_url: https://www.youtube.com/@fbcpierola
- name: instagram
  public_url: https://www.instagram.com/fbcpierola
- name: facebook
  public_url: https://www.facebook.com/fbcpierola
- name: tiktok
  public_url: https://www.tiktok.com/@fbcpierola
theme: null
title: FBC Piérola
url: https://fbcpierola.com
